### ISSUE TITLE
Factor out the reagent console

### ISSUE THREAD

**Issue by arichiardi** [joakin/cljs-browser-repl#1]
Hello @joakin (I reciprocate your issue on replumb :smile:) !

I have had a look at your code. It looks great and I was wondering if you were interested in factoring out the reagent console only.

Why do I think it is a good thing?

For starters it could be included freely in educational posts like [this one](http://blog.scalac.io/2015/10/19/cljs-on-gh-pages.html). Second, we could have a library that, combined with replumb, is the basis for richer console-based apps in the ClojureScript ecosystem (apps like [planck](https://github.com/mfikes/planck) could embed both). Finally, we can test it out and maintain it properly.

Thanks!
Andrea.

**Comment by joakin** [comment]
I don't see how planck could use something like this web repl, what do you mean?

Extracting the repl as a re-usable widget to publish standalone seems like a good idea :grinning:. Right now is pretty coupled to the app architecture but it shouldn't be a problem.

How would you envision the user API? How about something like:

``` clojure
[browser-repl
  {:state state
   :on-external-link-click (fn [])}]
```

Being state that the component needs an atom with the following keys:

```
{:history []
 :current-ns ""
 :input ""
 :current-notebook {:id nil
                    :cmds nil
                    :position 0}}
```

Or do you mean extracting the history/notebook parsing & logic? So that you could write this kind of repl with other frontends?

**Comment by arichiardi** [comment]
Yes you're right, no plank at all :)

A browser console component yes! Basically in a current project of mine I am using [jq-console](https://github.com/replit/jq-console) and I like the `.Prompt` method because it is pretty generic and you can basically plug anything you like in there, not just clojure. You can see an example in [replumb demo](https://github.com/ScalaConsultants/replumb/blob/master/repl-demo/browser/cljs/replumb_repl/console/cljs.cljs#L21).

So the main idea is to reproduce everything in there, mainly, as you said, history and multiline (notebook can be in a second stage, let's get the basic first).
Any nice feature that can be useful in a console/repl could go in there. Another idea I had was kind of a mode line (like emacs) in case your app wants to show it, but I guess can be easily implemented outside of this, and later.

The problem for me was the display. I could not, for example, plug highlighting in because there was no way to override the displayed html: instead of the plain `(def a "3")` I need the result of, let's say, [hljs.highlightBlock(block);](https://highlightjs.org/usage/), which is html again.
In our implementation we could even embed highlightjs in the reagent component, with the highlightjs class (in our case `clojure`) configurable from the constructor.

So a draft api could be:

```
[console-component
  {:welcome-string...and the others from https://github.com/replit/jq-console#instantiating
   :history true
   :result-fn! (fn [input after enter] ...)
   :multiline-fn! (fn [input after enter] ...)
   :on-external-link-click (fn [])}]

```

Then we will, see, but it is nice to brainstorm first, thanks for this.

**Comment by joakin** [comment]
Closing out for now, thanks for your work on replumb!
