### ISSUE TITLE
Diving into CLJS: don't make me click twice at every step

### ISSUE THREAD

**Issue by gamecubate** [joakin/cljs-browser-repl#2]
The Diving into Clojurescript project makes use of this REPL. Not sure posting here is appropriate but not having any other options, here goes (nothing):

I wish one wouldn't have to repeatedly tap or click the Next button to go to the next step of the tutorial, then tapping/clicking into the repl input field to input more cljs code. Not a great user experience and hopefully not a very difficult fix to implement.

**Comment by joakin** [comment]
@gamecubate What would you do instead? What is the fix you would do? It is the best way I found to pause mid lessons and allow students to input code and play with the examples.

You can also use `n` to move next, and `i` to focus on the repl input if you're not. Hopefully that'll help you!

**Comment by gamecubate** [comment]
If one could switch the focus from repl input to page input with the keyboard, that would work. Right now, `i` will switch focus to the repl input but once in there, you still have to tap or click if you want to advance to the next step.

That said, I reread the intent of the Diving into CLJS tutorial and see that the REPL is only there to let students experiment with code. IOW it is not necessary to interact with the repl at every step of the tutorial. In that context, things are okay.

For learning by coding, I found http://clojurescriptkoans.com/ which does things quite differently and perhaps is more in tune with what I wanted.

Thanks again and sorry for the digression.

**Comment by joakin** [comment]
No problem @gamecubate . For switching away from input just pressing Esc works fine (at least on OSX).

Good luck learning!
