### ISSUE TITLE
Traduccion al español de el notebook "Diving into Clojurescript"

### ISSUE THREAD

**Issue by joakin** [joakin/cljs-browser-repl#3]
## Que hay que traducir

Ver [`/cljs-browser-repl/resources/public/notebooks/diving-into-clojurescript/`](
https://github.com/joakin/cljs-browser-repl/tree/master/resources/public/notebooks/diving-into-clojurescript)

Hay 12 archivos en formato edn ([tutorial](https://learnxinyminutes.com/docs/edn/)), muy parecido a JSON.

## Como

La idea es crear una nueva carpeta `/cljs-browser-repl/resources/public/notebooks/diving-into-clojurescript-esp/` e ir copiando los archivos y traduciendolos uno cada commit. Verifica que los archivos cargan y despues envia una *Pull request* para revisarlo.

Traduce los textos que sean de `:type :markdown` dentro de la cadena, manteniendo el formato en markdown dentro de lo posible.

Por ejemplo: https://github.com/joakin/cljs-browser-repl/blob/master/resources/public/notebooks/diving-into-clojurescript/3.edn#L2-L6 se cambiaria por:

```diff
 [{:type :markdown :value
-  "# Truth and lies
+  "# Verdadero y falso
-  We've seen CLJS's `true` and `false` are the same as JS's booleans.
+  Hemos visto que `true` y `false` en CLJS son lo mismo que los booleanos en JS.
-  To compare in CLJS we can use the functions `=`, `not` and `not=`."}
+  Para comparar igualdad en CLJS podemos usar las funciones `=`, `not` y `not=`."}
```

## Verificar que funciona

Para probarlo, sirve `resources/public/` con un servidor local (`python -m SimpleHTTPServer` por ejemplo) y luego visita `localhost:8080/#/notebook/diving-into-clojurescript-esp/file/<nombre-del-archivo>`. Si el archivo edn tiene el formato correcto, deberia cargar la leccion sin problemas.

* http://localhost:8080/#/notebook/diving-into-clojurescript-esp/file/index
* http://localhost:8080/#/notebook/diving-into-clojurescript-esp/file/5

---

**Comment by rafaelpalomino** [comment]
Hola Joaquín. Por fin puedo ponerme con este asunto de la traducción. 
Este fin de semana trataré de traducir todo lo que pueda.

**Comment by kutyel** [comment]
Buenas Joaquín! Gracias por el workshop de ayer, poco podré tocar el cljs del repl pero tengo ganas de colaborar y me ofrezco para traducir! Si tengo problemas con el setup o lo que sea te aviso, ok? 😉

**Comment by joakin** [comment]
@kutyel 👍👏 gracias! Los archivos estan compilados en el repo por lo que con servir la carpeta con un servidor deberias ser capaz de verlo como comento en el primer comentario. No hay ni necesidad de correr `lein` para esto.

Los archivos [`.edn`](https://en.wikipedia.org/wiki/Extensible_Data_Notation) como veras son un subset de clojure, las mismas estructuras de datos que vimos ayer. Ya me dices si tienes algun problema 😃

**Comment by kutyel** [comment]
Genial, gracias! He hablado con @rafaelpalomino y va a hacer un PR con lo que ya tenía hecho, a partir de ahí cojo yo el testigo 😉
